
/*20180104*/

/*USE ODS;

DROP TABLE IF EXISTS ODS_HC_SERVICIOS;

TRUNCATE ODS_HC_SERVICIOS;

CREATE TABLE ODS_HC_SERVICIOS
(ID_SERVICIO INT(10) UNSIGNED NOT NULL PRIMARY KEY 
, ID_CLIENTE INT(10) 
, ID_PRODUCTO INT(10) 
, PUNTO_ACCESO VARCHAR(512)
, ID_CANAL INT(10)
, ID_AGENTE INT(10) 
, ID_DIRECCION_SERVICIO INT(10)
, FC_INICIO DATETIME
, FC_INSTALACION DATETIME
, FC_FIN DATETIME
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);


ANALYZE TABLE ODS_HC_SERVICIOS; 


USE ODS;
DROP TABLE IF EXISTS ODS_DM_PRODUCTOS;

CREATE TABLE ODS_DM_PRODUCTOS
(ID_PRODUCTO INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
, DE_PRODUCTO VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

USE ODS;
DROP TABLE IF EXISTS ODS_DM_CANALES;

CREATE TABLE ODS_DM_CANALES
(ID_CANAL INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
, DE_CANAL VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);*/




/*CREAMOS LAS FK DEL MODELO SERVICIOS*/

/*
USE ODS;
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_pro_idx (ID_PRODUCTO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_pro FOREIGN KEY (ID_PRODUCTO)
	REFERENCES ODS.ODS_DM_PRODUCTOS (ID_PRODUCTO);
    
USE ODS;
ALTER TABLE ODS.ODS_DM_SERVICIOS ADD INDEX fk_ser_can_idx (ID_CANAL ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_can FOREIGN KEY (ID_CANAL)
	REFERENCES ODS.ODS_DM_CANALES (ID_CANAL);

USE ODS;
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_cli FOREIGN KEY (ID_CLIENTE)
	REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE);
    
USE ODS;
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_dir_idx (ID_DIRECCION_SERVICIO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_dir FOREIGN KEY (ID_DIRECCION_SERVICIO)
	REFERENCES ODS.ODS_HC_DIRECCIONES (ID_DIRECCION);
    

*/


/*POBLADO DE DATOS*/

/*
USE ODS;

INSERT INTO ODS_DM_CANALES (DE_CANAL, FC_INSERT,FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(CHANNEL)) CANAL, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(CHANNEL)<>'';



INSERT INTO ODS_DM_CANALES VALUES (98, 'NO APLICA', NOW(),NOW());
INSERT INTO ODS_DM_CANALES VALUES (99, 'DESCONOCIDO', NOW(),NOW());

analyze TABLE ODS_DM_CANALES;

USE ODS;

INSERT INTO ODS_DM_PRODUCTOS (DE_PRODUCTO, FC_INSERT,FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_NAME)) PRODUCTO, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(PRODUCT_NAME)<>'';

INSERT INTO ODS_DM_PRODUCTOS VALUES (98, 'NO APLICA', NOW(),NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (99, 'DESCONOCIDO', NOW(),NOW());

ANALYZE TABLE ODS_DM_PRODUCTOS;
*/
USE ODS;

TRUNCATE ODS.ODS_HC_SERVICIOS;

INSERT INTO ODS.ODS_HC_SERVICIOS (ID_SERVICIO, ID_CLIENTE,ID_PRODUCTO,PUNTO_ACCESO, ID_CANAL,ID_AGENTE,ID_DIRECCION_SERVICIO,FC_INICIO,FC_INSTALACION,FC_FIN,FC_INSERT,FC_MODIFICACION) 
SELECT DISTINCT PRO.PRODUCT_ID ID_SERVICIO
, PRO.CUSTOMER_ID ID_CLIENTE
, PRODUCTOS.ID_PRODUCTO ID_PRODUCTO
, PRO.ACCESS_POINT PUNTO_ACCESO
, CAN.ID_CANAL
, AGE.ID_AGENTE_CC
, DIRSER.ID_DIRECCION
, CASE WHEN length(TRIM(PRO.START_DATE))<>0 THEN STR_TO_DATE(PRO.START_DATE,'%d/%m/%Y') ELSE str_to_date('31/12/9999', '%d/%m/%Y') end FC_INICIO
, CASE WHEN length(TRIM(PRO.INSTALL_DATE))<>0 THEN STR_TO_DATE(TRIM(REPLACE(PRO.INSTALL_DATE,'UTC','')),'%Y-%m-%d %T') ELSE str_to_date('31/12/9999', '%d/%m/%Y %r') end FC_INSTALACION
, CASE WHEN length(TRIM(PRO.END_DATE))<>0 THEN STR_TO_DATE(TRIM(REPLACE(PRO.END_DATE,'UTC','')),'%Y-%m-%d %T') ELSE str_to_date('31/12/9999', '%d/%m/%Y %r') end FC_FIN
, NOW()
, NOW()     
FROM STAGE.STG_PRODUCTOS_CRM PRO
INNER JOIN ODS.ODS_DM_CANALES CAN ON CASE WHEN LENGTH(TRIM(PRO.CHANNEL))<>0 THEN UPPER(TRIM(PRO.CHANNEL)) ELSE 'DESCONOCIDO' END=CAN.DE_CANAL #
INNER JOIN ODS.ODS_DM_PRODUCTOS PRODUCTOS ON  PRO.PRODUCT_NAME=PRODUCTOS.DE_PRODUCTO
LEFT JOIN ODS.ODS_DM_AGENTES_CC AGE ON CASE WHEN LENGTH(TRIM(PRO.AGENT_CODE))<>0 THEN UPPER(PRO.AGENT_CODE) ELSE 'DESCONOCIDO' END=AGE.ID_AGENTE_CC
INNER JOIN ODS.ODS_HC_DIRECCIONES DIR ON CASE WHEN TRIM(PRO.PRODUCT_ADDRESS)<>'' THEN UPPER(TRIM(PRO.PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END=DIR.DE_DIRECCION#
LEFT OUTER JOIN ODS.TMP_DIRECCIONES_SERVICIOS2 DIRSER ON DIRSER.ID_PRODUCTO=PRO.PRODUCT_ID;

*/


/* ANYADIR CAMPOS A PAISES*/


USE ODS;
SELECT * FROM ODS_DM_PAISES;
INSERT INTO ODS_DM_PAISES (DE_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT CASE WHEN UPPER(TRIM(PROD.PRODUCT_COUNTRY)) = 'UNITED STATES' THEN 'US' END as PAIS
, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PROD
WHERE CASE WHEN UPPER(TRIM(PROD.PRODUCT_COUNTRY)) = 'UNITED STATES' THEN 'US' ELSE UPPER(TRIM(PROD.PRODUCT_COUNTRY)) END NOT IN (SELECT DE_PAIS FROM ODS_DM_PAISES) and TRIM(PROD.PRODUCT_COUNTRY)<>'';

COMMIT;

INSERT INTO ODS_DM_PAISES VALUES (99, ‘DESCONOCIDO’, NOW(), NOW());
INSERT INTO ODS_DM_PAISES VALUES (98, ‘NO APLICA’, NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_PAISES;









/*
INSERT INTO ODS_DM_CIUDADES_ESTADOS(DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT CASE WHEN TRIM(PROD.PRODUCT_CITY)<>'' THEN UPPER(TRIM(PROD.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END CIUDAD
, CASE WHEN TRIM(PROD.PRODUCT_STATE)<>'' THEN UPPER(TRIM(PROD.PRODUCT_STATE)) ELSE 'DESCONOCIDO' END ESTADO
, PAI.ID_PAIS
, NOW()
, NOW()
FROM STAGE.STG_PRODUCTOS_CRM PROD
INNER JOIN ODS.ODS_DM_PAISES PAI ON CASE WHEN TRIM(PROD.PRODUCT_COUNTRY)<>'' THEN
 CASE WHEN UPPER(TRIM(PROD.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US' ELSE UPPER(TRIM(PROD.PRODUCT_COUNTRY)) END ELSE 'DESCONOCIDO' END=PAI.DE_PAIS
WHERE (TRIM(PROD.PRODUCT_CITY) NOT IN (SELECT DE_CIUDAD FROM ODS_DM_CIUDADES_ESTADOS) OR TRIM(PROD.PRODUCT_STATE) NOT IN (SELECT DE_ESTADO FROM ODS_DM_CIUDADES_ESTADOS));
*/

/*ANAYADIR DIRECCIONES DE PRODUCTOS A LA TABLA DE DIRECCIONES*/

/* 

INSERT INTO ODS_HC_DIRECCIONES (DE_DIRECCION, DE_CP, ID_CIUDAD_ESTADO, FC_INSERT, FC_MODIFICACION)
SELECT UPPER(TRIM(PROD.PRODUCT_ADDRESS)) DIRECCION
, CASE WHEN TRIM(PROD.PRODUCT_POSTAL_CODE)<>'' THEN TRIM(PROD.PRODUCT_POSTAL_CODE) ELSE 99999 END CP, CIU.ID_CIUDAD_ESTADO, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PROD

INNER JOIN ODS.ODS_DM_PAISES PAIS ON CASE WHEN TRIM(PROD.PRODUCT_COUNTRY)<>'' THEN 
CASE WHEN UPPER(TRIM(PROD.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US' END ELSE 'DESCONOCIDO' END=PAIS.DE_PAIS

INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON CASE WHEN TRIM(PROD.PRODUCT_CITY)<>'' THEN UPPER(TRIM(PROD.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END=CIU.DE_CIUDAD
AND CASE WHEN TRIM(PROD.PRODUCT_STATE)<>'' THEN TRIM(PROD.PRODUCT_STATE) ELSE 'DESCONOCIDO' END=CIU.DE_ESTADO
WHERE (TRIM(PROD.PRODUCT_ADDRESS) NOT IN (SELECT DE_DIRECCION FROM ODS_HC_DIRECCIONES) OR TRIM(PROD.PRODUCT_POSTAL_CODE) NOT IN (SELECT DE_CP FROM ODS_HC_DIRECCIONES));


*/

/* PONER ID_DIRECCIONES EN ODS_HC_SERVICIOS*/

/*
DROP TABLE IF EXISTS TMP_DIRECCIONES_SERVICIOS;
CREATE TABLE TMP_DIRECCIONES_SERVICIOS AS
SELECT DIR.ID_DIRECCION
, DIR.DE_DIRECCION
, DIR.DE_CP
, CIU.DE_CIUDAD
, CIU.DE_ESTADO
, PAI.DE_PAIS
FROM ODS.ODS_HC_DIRECCIONES DIR
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON DIR.ID_CIUDAD_ESTADO=CIU.ID_CIUDAD_ESTADO
INNER JOIN ODS_DM_PAISES PAI ON CIU.ID_PAIS=PAI.ID_PAIS;

ANALYZE TABLE TMP_DIRECCIONES_SERVICIOS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_SERVICIOS2;


CREATE TABLE TMP_DIRECCIONES_SERVICIOS2 AS
SELECT PRO.PRODUCT_ID ID_PRODUCTO
, DIR.ID_DIRECCION
FROM STAGE.STG_PRODUCTOS_CRM PRO
INNER JOIN ODS.TMP_DIRECCIONES_SERVICIOS DIR ON CASE WHEN TRIM(PRO.PRODUCT_ADDRESS)<>'' THEN UPPER(TRIM(PRO.PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END=DIR.DE_DIRECCION
												AND CASE WHEN TRIM(PRO.PRODUCT_POSTAL_CODE)<>'' THEN UPPER(TRIM(PRO.PRODUCT_POSTAL_CODE)) ELSE 99999 END=DIR.DE_CP
                                               AND CASE WHEN TRIM(PRO.PRODUCT_CITY)<>'' THEN UPPER(TRIM(PRO.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END=DIR.DE_CIUDAD
                                                AND CASE WHEN TRIM(PRO.PRODUCT_STATE)<>'' THEN UPPER(TRIM(PRO.PRODUCT_STATE)) ELSE 'DESCONOCIDO' END=DIR.DE_ESTADO
                                                AND CASE WHEN TRIM(PRO.PRODUCT_COUNTRY)<>'' THEN REPLACE(PRO.PRODUCT_COUNTRY, 'United States','US') ELSE 'DESCONOCIDO' END=DIR.DE_PAIS;    
    

analyze TABLE TMP_DIRECCIONES_SERVICIOS2;


