
/*20180104*/


USE ODS;

DROP TABLE IF EXISTS ODS_HC_LLAMADAS;
TRUNCATE TABLE ODS_HC_LLAMADAS;

CREATE TABLE ODS_HC_LLAMADAS
(ID_LLAMADA INT(10) UNSIGNED NOT NULL 
, ID_IVR INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
, TELEFONO_LLAMADA BIGINT(20) 
, ID_CLIENTE INT(10) 
, FC_INICIO_LLAMADA DATETIME
, FC_FIN_LLAMADA DATETIME
, ID_DEPARTAMENTO_CC INT(10)
, FLG_TRANSFERIDO TINYINT(1) 
, ID_AGENTE INT(10) 
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

USE ODS;


DROP TABLE IF EXISTS ODS_DM_AGENTES_CC;

CREATE TABLE ODS.ODS_DM_AGENTES_CC
(ID_AGENTE_CC INT(10) PRIMARY KEY AUTO_INCREMENT
, DE_AGENTE VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);


SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS ODS_DM_DEPARTAMENTOS_CC;


CREATE TABLE ODS_DM_DEPARTAMENTOS_CC
(ID_DEPARTAMENTO_CC INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
, DE_DEPARTAMENTO_CC VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

SET FOREIGN_KEY_CHECKS=1;

/*RELACION DE LAS TABLAS*/


USE ODS;
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_llama_de_idx (ID_DEPARTAMENTO_CC ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_llama_de FOREIGN KEY (ID_DEPARTAMENTO_CC)
	REFERENCES ODS.ODS_DM_DEPARTAMENTOS_CC (ID_DEPARTAMENTO_CC);
    
USE ODS;
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_llama_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_llama_cli_can FOREIGN KEY (ID_CLIENTE)
	REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE);

USE ODS;
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_llama_agent_idx (ID_AGENTE ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_llama_agent FOREIGN KEY (ID_AGENTE)
	REFERENCES ODS.ODS_DM_AGENTES_CC (ID_AGENTE_CC);
    
    
/* POBLACION TABLAS*/ 



INSERT INTO ODS_DM_DEPARTAMENTOS_CC (DE_DEPARTAMENTO_CC, FC_INSERT, FC_MODIFICACION)
select distinct UPPER(TRIM(SERVICE)) DE_DEPARTAMENTO, NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR CONT
WHERE LENGTH(TRIM(SERVICE))<>0;
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (98,'NO APLICA', NOW(),NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (99,'DESCONOCIDO', NOW(),NOW()); 

ANALYZE TABLE ODS_DM_DEPARTAMENTOS_CC; 
    


INSERT INTO ODS_DM_AGENTES_CC (DE_AGENTE, FC_INSERT, FC_MODIFICACION)
select distinct UPPER(TRIM(AGENT)) DE_AGENTE, NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR CONT
WHERE LENGTH(TRIM(AGENT))<>0;

INSERT INTO ODS_DM_AGENTES_CC VALUES (998,'NO APLICA', NOW(),NOW());
INSERT INTO ODS_DM_AGENTES_CC VALUES (999,'DESCONOCIDO', NOW(),NOW()); 

ANALYZE TABLE ODS_DM_AGENTES_CC;




TRUNCATE ODS_HC_LLAMADAS;

SET FOREIGN_KEY_CHECKS=0;




INSERT INTO ODS_HC_LLAMADAS(ID_LLAMADA,TELEFONO_LLAMADA,ID_CLIENTE,FC_INICIO_LLAMADA,FC_FIN_LLAMADA,ID_DEPARTAMENTO_CC,FLG_TRANSFERIDO,ID_AGENTE,FC_INSERT,FC_MODIFICACION)
select CONT.ID ID_LLAMADA
, CASE WHEN TRIM(CONT.PHONE_NUMBER)<>'' THEN TRIM(CONT.PHONE_NUMBER) ELSE  9999999999 END TELEFONO_LLAMADA
, 999999999
, CASE WHEN TRIM(CONT.START_DATETIME)<>'' THEN STR_TO_DATE(CONT.START_DATETIME, '%Y-%m-%d %T.%f') ELSE  str_to_date('9999/12/31 00:00:00', '%Y/%m/%d %T') END FC_INICIO_LLAMADA
, CASE WHEN TRIM(CONT.END_DATETIME)<>'' THEN STR_TO_DATE(CONT.END_DATETIME, '%Y-%m-%d %T.%f') ELSE  str_to_date('9999/12/31 00:00:00', '%Y/%m/%d %T') END FC_FIN_LLAMADA
, DEP.ID_DEPARTAMENTO_CC
, CASE WHEN TRIM(UPPER(CONT.FLG_TRANSFER))='TRUE' THEN 1 ELSE 0 END FLG_TRANSFERIDO
, AGENTE.ID_AGENTE_CC
, NOW() 
, NOW()
from STAGE.STG_CONTACTOS_IVR CONT
INNER JOIN ODS.ODS_DM_DEPARTAMENTOS_CC DEP ON CASE WHEN TRIM(CONT.SERVICE)<>'' THEN UPPER(TRIM(CONT.SERVICE)) ELSE 'DESCONOCIDO' END=DEP.DE_DEPARTAMENTO_CC
INNER JOIN ODS.ODS_DM_AGENTES_CC AGENTE ON CASE WHEN TRIM(AGENT)<>'' THEN UPPER(TRIM(CONT.AGENT)) ELSE 'DESCONOCIDO' END=AGENTE.DE_AGENTE;

ANALYZE TABLE ODS_HC_LLAMADAS;






SET FOREIGN_KEY_CHECKS=1;







 


