


USE ODS;



/*
select COUNT(FACT.BILL_REF_NO) ID_FACTURA
, CICLOS.ID_CICLO_FACTURACION
from STAGE.STG_FACTURAS_FCT FACT
LEFT OUTER JOIN ODS.ODS_HC_CLIENTES CLI ON CASE WHEN LENGTH(TRIM(CUSTOMER_ID))<>0 THEN UPPER(TRIM(CUSTOMER_ID)) ELSE 'DESCONOCIDO' END=CLI.ID_CLIENTE
INNER JOIN ODS.ODS_DM_CICLOS_FACTURACION CICLOS ON CASE WHEN LENGTH(TRIM(BILL_CYCLE))<>0 THEN UPPER(TRIM(BILL_CYCLE)) ELSE 'DESCONOCIDO' END=CICLOS.ID_CICLO_FACTURACION;
#INNER JOIN ODS.ODS_DM_METODOS_PAGO METODO ON CASE WHEN LENGTH(TRIM(BILL_METHOD))<>0 THEN UPPER(TRIM(BILL_METHOD)) ELSE 'DESCONOCIDO' END=METODO.ID_METODO_PAGO
*/





